### ISSUE TITLE
Make token matching for relative temporal scopes take current time into account

### ISSUE THREAD

**Issue by stepenta** [fp7mplane/protocol-ri#12]
When a Specification is sent to the ping, with exactly the same parameters of a Specification already executed (and completed), it will not be executed again since it results as already running. (Even the 'when' parameter must be the same, e.g. now + 10s / 1s)

**Comment by netvisor** [comment]
Dear all, 

Why is it not a better idea to let the Probe convert the relative tokens into absolute values, before using them as hash keys? The client could keep sending relative when-s this way.

**Comment by britram** [comment]
This is done in client.py in the SDK branch now.

The reason this doesn't happen on the component side is that the token is (per the protocol spec) a client-generated value which the component simply parrots back. Think of it like the subject of an email message. The RI has some logic for generating tokens automatically from message contents but this could be overridden by a more sophisticated client that binds tokens to internal state kept at the client.
