### ISSUE TITLE
Implement callback control

### ISSUE THREAD

**Issue by britram** [fp7mplane/protocol-ri#15]
Callback control is specified in the present rev of the protocol spec; implement in the generic client and server as described.

**Comment by britram** [comment]
Special-casing for callback control currently in client.py; component.py's InitiatorHttpComponent class still needs callback control scheduling.

**Comment by stepenta** [comment]
Implemented in component-initiated component as a separated capability.
When requested by the client, the component adjusts its waiting time to the next poll accordingly. After that time has passed and the next poll is done, the timer is reset to its original value.
