### ISSUE TITLE
Delete receipt after redemption gives an exception 

### ISSUE THREAD

**Issue by MKV21** [fp7mplane/protocol-ri#23]
If we receive results from a repeated measurement we don't delete the receipt at the moment. If it is a finite repeated measurement at some point the client gets an exception (should be a 404 exception once status codes are implemented) that the job does no longer exist (and all results have been retrieved). The receipt can be deleted then.

**Comment by stepenta** [comment]
Solved.
For repeated measurements, the client keeps the receipt until the measurement is running, and can ask for partial results to the component. The component will remove the result only when the measurement is completed and the result is sent to the client.
