### ISSUE TITLE
Add callbacks to Job and MultiJob

### ISSUE THREAD

**Issue by britram** [fp7mplane/protocol-ri#24]
Job and MultiJob should take an optional callback closure, which gets called after the job completes with the result or exception the job produced.

**Comment by britram** [comment]
mplane.model.Scheduler.receive_message() (which might need to be renamed now to process_message()?) needs to take this optional callback, as well.

**Comment by MKV21** [comment]
The callback does not get the result or exception as argument but a receipt. With this mplane.model.Scheduler.process_message() can be called to get the results or exceptions. This way the scheduler can handle job deletion properly and the calling function could wait for multiple results before calling process_message with the receipt (the receipt for a MultiJob will always be the same as it is generated with the Specification).

**Comment by stepenta** [comment]
Implemented in component-initiated component. 
Not needed in client-initiated workflow: the component doesn't need to periodically check the state of the jobs, since it just waits for the client asking results.
