### ISSUE TITLE
duplicates in core registry.json

### ISSUE THREAD

**Issue by mdusi** [fp7mplane/protocol-ri#28]
In the sdk branch, the field "duration.ms" appears twice in the registry.json file, with two different types (natural and prim_time). It should be of type natural only.

**Comment by britram** [comment]
In general, the core registry needs a fair amount of work. Have been putting this off because it might break running code, but we can discuss in Vienna.

**Comment by MKV21** [comment]
We (FHA) did not want to tamper with the core registry so we made a subregistry for GLIMPSE (work in progress). Some of the elements might be of interest for the core registry (the onesnot prefaced "glimpse."): https://www.measure-it.net/static/glimpse_registry.json

**Comment by britram** [comment]
Duplicates have been removed; the disposition of component specific registries is under discussion in #44
