### ISSUE TITLE
Module ping breaks when using "now ... future / 1s" as "when" argument.

### ISSUE THREAD

**Issue by gubser** [fp7mplane/protocol-ri#31]
Hi there, my first steps using mPlane. Obviously "when"="now ... future / 1s" is not supported by ping.py. However using a finite interval "when"="now + 1m / 1s" works.

# Setup #
python3 -m mplane.clientshell --config conf/supervisor.conf
python3 -m mplane.component --config conf/component.conf

Then starting measurement from clientshell with:
|mplane| runcap ping-detail-ip4
|when| = now ... future / 1s
destination.ip4 = 8.8.8.8

# Result #
Results in Exception in python interpreter running mplane.component:
Got exception in _run(), returning <Exception: ce23dc3daa348ac480e1b34edf261d89 'NoneType' object has no attribute 'total_seconds'>
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/elio/SA/protocol-ri/mplane/scheduler.py", line 127, in _run
    raise e
  File "/home/elio/SA/protocol-ri/mplane/scheduler.py", line 120, in _run
    self._check_interrupt)
  File "/home/elio/SA/protocol-ri/mplane/components/ping.py", line 160, in run
    duration = spec.when().duration().total_seconds()
AttributeError: 'NoneType' object has no attribute 'total_seconds'
....
Scheduling <Job for <specification: measure (ping-detail-ip4-1) when now ... future / 1s token 172bdb43 schema db8ef547 p(v)/m/r 2(2)/0/2>> immediately
Got exception in _run(), returning <Exception: 172bdb436c3f1b75f5a281b1c7ac2cab 'NoneType' object has no attribute 'total_seconds'>
<hr />
Problem is in ping.py:160: duration() returns None object and the code tries to call total_seconds().

**Comment by britram** [comment]
With respect to ping.py, this is basically an input validation error - since there is no indirect export support in this module, infinite temporal scopes are kind of meaningless. This behavior of When.duration() is now documented, at least.
