### ISSUE TITLE
Verify correct handling of the link: section by client.py and component.py

### ISSUE THREAD

**Issue by britram** [fp7mplane/protocol-ri#39]
A message's link: section should always override any local configuration for where to send a spec against a cap / indirect, or a result against spec. Verify that this is properly handled everywhere

**Comment by stepenta** [comment]
If we use complete urls, the component and the supervisor should know their own public IP. If the component (or the supervisor) is behind a NAT, it has no means to obtain the IP needed for the link section. 
Should we add a line in the configuration file, something like public_ip?

**Comment by stepenta** [comment]
A new field has been added to the configuration files: source_ip. This field is used to forge the uri for the link section.
Also, if environment variable SOURCE_IP is set, this field is ignored in favour of the env variable: this allows to set source ip for multiple components simultaneously, without the need to edit lots of conf files. (demo oriented funcionality)
