### ISSUE TITLE
mpcom/mpcli require source_ip configuration?

### ISSUE THREAD

**Issue by britram** [fp7mplane/protocol-ri#43]
mpcom and mpcli crash if no source_ip is given. In the case of mpcli, this happens even when using a client-initiated workflow, which is doubly nonsensical. I also don't think source_ip should be a configuration parameter at all.

On code review, I see that this is only used in the component and client to calculate link sections. This should made *explicit*. i.e., component-initiated clients (and client-initiated components) can have their link URLs for accepting capabilities and results (and specifications and receipts) explicitly set by configuration; the configured URL value then gets exposed via the link: section in the appropriate message, *and* causes Tornado to listen to the right URL. 

The default (i.e., when no configuration is given) is to listen at the current default (i.e. / on all addresses) and not send link: sections in messages.

It might be necessary to set link URLs for each message type: capability_link_uri, specification_link_uri, etc.

**Comment by stepenta** [comment]
I think that (talking with the demo virtual machine in mind) having explicit link URLs is not a good idea, since this parameter should be changed in every conf file every time the code is deployed on a new host, while with the source_ip configurable by environment variable you only have to make 1 change for all the modules.

Also, I don't understand why a component should start listen on a different host/port...imho this is a marginal case, but adds non negligible complexity to the code (one additional server instance).

What do you think?

(Meanwhile I will fix the crash for the client-init workflow)

**Comment by britram** [comment]
> On 09 Jun 2015, at 12:08, stepenta <notifications@github.com> wrote:
> 
> I think that (talking with the demo virtual machine in mind) having explicit link URLs is not a good idea, since this parameter should be changed in every conf file every time the code is deployed on a new host, while with the source_ip configurable by environment variable you only have to make 1 change for all the modules.

You *still* have to change the source IP in the configuration file. Either you have to edit the config or you don't; I don't buy the argument

If we're really concerned with getting a routable address to base autogenerated link URLs on alternate method to do this would be to automatically detect the routable source IP for the link URL. This can be done by GET / from a Ripe Atlas anchor (http://194.242.34.190 for example), then getting the "client" key from the resulting JSON. (I would want the ability to do atlas autodetect, and the atlas anchor IP to use to do this, to be configurable)

> Also, I don't understand why a component should start listen on a different host/port...imho this is a marginal case, but adds non negligible complexity to the code (one additional server instance).

Hm.

Actually, the right think to do is to allow a link-uri to be explicitly set, but _not_ to use that information to set the listener configuration. A capability generated with a link to another URL should indeed be used to redirect clients to that URL.

I agree that reworking the code so that a single component/client can listen from multiple passive sockets is way too much complexity for the win. So if the listener URLs are configurable, it should be an error if they don't have the same host/port component.

**Comment by stepenta** [comment]
Taking the IP from RIPE Atlas anchor is a nice idea, but i think it could add other problems related to redirections. 
So in the end I removed the source_ip parameter and added an explicit link setting in the conf files.
