### ISSUE TITLE
Component-specific registries problem

### ISSUE THREAD

**Issue by stepenta** [fp7mplane/protocol-ri#44]
When a component uses a specific registry in addition to the core registry (like tStat does), that registry is needed also on the supervisor and on the client. This is not very efficient, since the supervisor and the client cannot know in advance all the components that will be available, and this could result in missing keys when receiving capabilities.
How should we handle this?

Also, at the moment each instance (component, supervisor, client) can load only one base registry and one specific registry. The preload_registry function should be modified to make it possible to specify several registries in the preload_registry setting in the configuration files (this is important especially for supervisor and client)

**Comment by britram** [comment]
The user specific registry is always referenced by URL, from which it will be retrieved if it is not preloaded. Preload is just a way to reduce network load. Declaring a user specific registry without placing its content at the referenced URL will of course break things.

The preload_registry function only takes a single argument because Windows INI files don't do lists. :( I'll fix this, probably by having any key that *starts* with preload_registry getting preloaded.

**Comment by stepenta** [comment]
Ok...where should be the URL referring to the probe-specific registry exposed (and retrieved)? I didnt' find anything for that in model.py

**Comment by netvisor** [comment]
How do you find the idea to add a getRegistry method to the network protocol, which allows a client to collect the registry from a probe (or superisor), if it finds unknown keys in the capabilities. 

This may not be difficult, the main question is whether it is possible to extend the registry in runtime, and how difficult it would be to merge registries... 

But we may be quite strict here, i.e. to refuse any different values for a single key.

Árpad

**Comment by straverso** [comment]
Wouldn't be much simpler to let the client collect all registries at the registration?

**Comment by britram** [comment]
mPlane is not a configuration management protocol.

It is always possible to extend the registry at runtime, as long as the component/client can resolve the registry URL and retrieve what's there. I'm not convinced that adding some sort of additional registry transfer primitive to the base protocol gains us much, and the additional complexity of having to store and forward registries (1) seems like an excellent place to hide difficult-to-reason-about trust bugs.

Registry preload is admittedly a bit of a hack, but it's a hack we can have working well in time for a November demo.

**Comment by straverso** [comment]
My idea of (1) is not to make the component forward its whole specific registry, but just the URL referencing it. 

In the current status of the implementation the component specific registry should be complementary to the core registry, and the only way we have to let the supervisor fetch it is to C&P the registry_uri referencing the component specific registry to the supervisor.conf. This does not make much sense as it can not work in all scenarios where the component user has no access to the supervisor.conf. The preload does not solve this issue.

**Comment by britram** [comment]
> On 17 Jun 2015, at 09:16, Stefano Traverso <notifications@github.com> wrote:
> 
> My idea of (1) is not to make the component forward its whole specific registry, but just the URL referencing it.

Ah. It does this anyway. Every message should contain a registry: key. (If that's not what it's doing, that's a bug).

**Comment by netvisor** [comment]
Please consider the fact that in production telco environments management system components (i.e. probes and their managers) typically cannot access the Internet, so they maynot be able to download the registries by URL.

**Comment by britram** [comment]
> On 17 Jun 2015, at 11:43, netvisor <notifications@github.com> wrote:
> 
> Please consider the fact that in production telco environments management system components (i.e. probes and their managers) typically cannot access the Internet, so they maynot be able to download the registries by URL.

In https://mplane.my-telco.com/registries/foo.json, mplane.my-telco-com doesn't necessarily have to resolve to a globally routable address. One of the reasons to scope registries to a URL is to allow people to use all the DNS tricks they already do for split-horizon service discovery in enterprise environments.

**Comment by stepenta** [comment]
Solved this...actually all the needed material was already there (thanks Brian!), I just put it together.
Let's suppose we have a component that needs a specific registry: it's enough to make sure that the registry-uri field in specific-registry.json is a valid uri to that registry, and to add this line:
"includes": ["http://ict-mplane.eu/registry/core"]
In the component.conf we don't need anymore the registry preload, and we can directly put specific-registry in the registry_uri setting.

In this way, all the capabilities coming from this component will have their registry field set to the specific-registry (that includes the core registry), and the supervisor (and the client) will be able to retrieve that and use it to handle the capability. 
There's no more need to put a registry_preload setting also in supervisor.conf and client.conf, everything will be handled in runtime
