### ISSUE TITLE
Infinite time mapped to 0

### ISSUE THREAD

**Issue by straverso** [fp7mplane/protocol-ri#45]
Having infinite future time mapped to 0 conflicts with the following code (line 153 of scheduler.py).

        # start interrupt timer
        if end_delay is not None and not hasattr(self.service, 'relay'):
            threading.Timer(end_delay, self.interrupt).start()
            print("Will interrupt "+repr(self)+" after "+str(end_delay)+" sec")

This code triggers an instantaneous interrupt (after 0 seconds indeed), which should never be triggered (being the future time equal to infinite).
I propose to map "inf" to datetime.datetime.max in model.py to solve this, but I don't know whether such modification could cause problems in other parts of the code.

**Comment by britram** [comment]
I *believe* this should work. Indeed, I'm not sure why infinite future should be mapped to 0 in the first place...

**Comment by straverso** [comment]
Actually the infinite future case is not handled at all by the "duration" parser, leading to "inf" being mapped to None, first, and 0, then. I have a patch fixing this which should not harm other parts of the code (it simply maps "inf" to a large number of days):

```
diff --git a/mplane/model.py b/mplane/model.py
index 5dba671..366fb90 100644
--- a/mplane/model.py
+++ b/mplane/model.py
@@ -348,6 +348,7 @@ VALUE_NONE = "*"
 TIME_PAST = "past"
 TIME_NOW = "now"
 TIME_FUTURE = "future"
+MAX_TIME = 100000

 WHEN_REPEAT = "repeat "
 WHEN_CRON = " cron "
@@ -479,7 +480,9 @@ def parse_dur(valstr):
         return None
     else:
         m = _dur_re.match(valstr)
-        if m:
+        if "inf" == valstr:
+            return timedelta(seconds=MAX_TIME*_dur_seclabel[0][0])
+        elif m:
             mg = m.groups()
             valsec = 0
             for i in range(4):
```

**Comment by britram** [comment]
hi Stefano,

is there no appropriate timedelta constant meaning "forever"? if not stick a #FIXME HACK on this so we can come back and find it later. :)

**Comment by straverso** [comment]
I agree it's an ugly hack. 
There exists timedelta.max actually. Problem is it raises some OverflowErrors here and there. And even if we properly handle these exceptions it will still conflict which the maximum timeout allowed in threading (TIMEOUT_MAX). 
I'll commit it with the #FIXME HACK.
Thanks
