### ISSUE TITLE
Handling crashing of supervisor and components 

### ISSUE THREAD

**Issue by straverso** [fp7mplane/protocol-ri#49]
Hi,
currently, when the supervisor dies (i.e., its process is killed), all registered components crash. This is not good for demo purposes. Being a distributed system, we need the system to (partially) survive in case of failures of (at least single) endpoints.

Similarly, when a component is killed, the supervisor does not un-register it. This should be handled using a timeout I think, to avoid occasional packet losses to be interpreted by the supervisor as a actual component failures.
Thanks,

Stefano

p.s. I'd tag stepenta too, but github does not allow to assign issues to multiple people...

**Comment by britram** [comment]
> On 06 Jul 2015, at 10:45, Stefano Traverso <notifications@github.com> wrote:
> 
> Hi,
> currently, when the supervisor dies (i.e., its process is killed), all registered components crash.
> 
If you're going to use the word "crash", you have to bring a stack trace. :)
> This is not good for demo purposes.
> 
Or at all.
> Being a distributed system, we need the system to (partially) survive in case of failures of (at least single) endpoints.
> 
Supervisor issues are @stepenta 's department.
> Similarly, when a component is killed, the supervisor does not un-register it.
> 
So we could (and should) have components in component-initiated workflows fire off withdrawals on orderly shutdown, which would be a separate (enhancement request) issue...
> This should be handled using a timeout I think, to avoid occasional packet losses to be interpreted by the supervisor as a actual component failures.
> 
But yes, the supervisor should also handle component-down without withdrawal conditions.

**Comment by stepenta** [comment]
I'll work on this, I have already a fix for the component crash,  and i'm working on the supervisor. 
Where should the commits go? Always on SDK, or should we move to master now that SDK and master are merged?

**Comment by stepenta** [comment]
With this commit:
- When the supervisor dies the components don't crash anymore, instead they try to reconnect
- If a component dies, its capabilities registered on the client expire after 10 seconds (hardcoded for now, we could change to configurable timeout)
- If a capability expires in the supervisor a Withdrawal is generated and sent to the client
