### ISSUE TITLE
Generic component framework in component.py

### ISSUE THREAD

**Issue by britram** [fp7mplane/protocol-ri#7]
httpsrv.py should implement a CLI, like client.py, for binding Python methods to capabilities in Services, and making them available and unavailable for testing.

**Comment by britram** [comment]
This isn't really a CLI; it's governed by the mPlane configuration file. @stepenta is already working on this in the sdk branch.

**Comment by britram** [comment]
There are two classes here: ListenerHttpComponent and InitiatorHttpComponent. ListenerHttpComponent is mostly done, inheriting most of its code from httpsrv.py (which should now be removed). 

InitiatorHttpComponent should do the following:

(1) connect to a supervisor (whose capabilities URL is given in the Component section of the configuration file) on startup and POST the capabilities describing its service(s) (in an envelope)

(2) periodically connect to a supervisor (whose specifications URL is given in the Component section of the configuration file) to GET specifications to run. If received, these should be evaluated to see if they are callback control specs (i.e. verb callback) and if so should modify the polling; if not, they should be handed to the scheduler for running. (Keep in mind here that a GET from a supervisor may result in multiple specifications in an envelope)

(3) When submitting specifications to the scheduler, the InitiatorHttpComponent hands in a callback which will receive a reply after job completion; when this callback is called, it should POST the reply to the supervisor (whose results URL is given in the Component section of the configuration file)

**Comment by stepenta** [comment]
Everything done and working.
